import {
  Wrench,
  ScanSearch,
  ClipboardCheck,
  Disc,
  Gauge,
  Snowflake,
  Thermometer,
  Zap,
  Wind,
  Fuel,
  CircleDot,
  Rocket,
  Paintbrush,
  Truck,
  ClipboardList,
  Cpu,
  type LucideIcon,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  icon: LucideIcon;
  summary: string;
  note?: string;
  items: string[];
};

export const services: Service[] = [
  {
    slug: "general-mechanical-repairs",
    title: "General Mechanical Repairs",
    icon: Wrench,
    summary:
      "Engine, transmission and drivetrain repairs handled by certified technicians.",
    items: [
      "Engine diagnostics & repairs",
      "Engine rebuilds & replacements",
      "Transmission repairs & replacement",
      "Clutch replacement",
      "Timing belt & timing chain replacement",
      "Head gasket repairs",
      "Turbocharger repairs",
    ],
  },
  {
    slug: "vehicle-diagnostics",
    title: "Vehicle Diagnostics",
    icon: ScanSearch,
    summary:
      "Computerized fault-finding to pinpoint issues fast and accurately.",
    items: [
      "Computer diagnostics (OBD scanning)",
      "Check engine light diagnosis",
      "Electrical fault finding",
      "Battery & charging system testing",
    ],
  },
  {
    slug: "maintenance-servicing",
    title: "Maintenance & Servicing",
    icon: ClipboardCheck,
    summary:
      "Scheduled minor and major services that keep every system running true.",
    items: [
      "Minor service",
      "Major service",
      "Oil & filter change",
      "Air, cabin & fuel filter replacement",
      "Spark plug replacement",
      "Coolant flush",
      "Brake fluid replacement",
      "Transmission fluid service",
      "Differential & transfer case oil service",
    ],
  },
  {
    slug: "brake-services",
    title: "Brake Services",
    icon: Disc,
    summary: "Pads, discs, calipers and ABS — inspected, repaired and bled to spec.",
    items: [
      "Brake pad replacement",
      "Brake disc (rotor) replacement",
      "Brake caliper repair",
      "ABS diagnosis & repair",
      "Brake system bleeding",
    ],
  },
  {
    slug: "suspension-steering",
    title: "Suspension & Steering",
    icon: Gauge,
    summary: "Smooth handling and precise steering, from bushings to bearings.",
    items: [
      "Shock absorber replacement",
      "Suspension repairs",
      "Steering rack repairs",
      "Power steering repairs",
      "Wheel bearing replacement",
      "Control arm & bushing replacement",
      "Ball joint replacement",
    ],
  },
  {
    slug: "air-conditioning",
    title: "Air Conditioning",
    icon: Snowflake,
    summary: "Full AC servicing to keep your cabin cool in every season.",
    items: [
      "AC gas refill (R134a & R1234yf)",
      "AC leak detection",
      "Compressor replacement",
      "Condenser replacement",
      "Evaporator repairs",
      "Climate control diagnostics",
    ],
  },
  {
    slug: "cooling-system",
    title: "Cooling System",
    icon: Thermometer,
    summary: "Radiators, pumps and hoses kept leak-free and running at temperature.",
    items: [
      "Radiator replacement",
      "Water pump replacement",
      "Thermostat replacement",
      "Cooling fan repairs",
      "Hose replacement",
      "Coolant leak repairs",
    ],
  },
  {
    slug: "electrical-services",
    title: "Electrical Services",
    icon: Zap,
    summary: "Alternators, wiring and lighting diagnosed and repaired with precision.",
    items: [
      "Alternator repair & replacement",
      "Starter motor repair",
      "Battery replacement",
      "Wiring repairs",
      "Fuse & relay replacement",
      "Lighting upgrades",
      "Sensor replacement",
    ],
  },
  {
    slug: "exhaust-system",
    title: "Exhaust System",
    icon: Wind,
    summary: "Exhaust, catalytic converter and muffler repairs done right.",
    items: [
      "Exhaust repair",
      "Catalytic converter replacement",
      "Muffler replacement",
      "Exhaust leak repairs",
    ],
  },
  {
    slug: "fuel-system",
    title: "Fuel System",
    icon: Fuel,
    summary: "Pumps, injectors and tanks serviced for consistent performance.",
    items: [
      "Fuel pump replacement",
      "Fuel injector cleaning",
      "Injector replacement",
      "Fuel tank repairs",
    ],
  },
  {
    slug: "tyres-wheels",
    title: "Tyres & Wheels",
    icon: CircleDot,
    summary: "Replacement, balancing, alignment and refurbishment for every wheel.",
    items: [
      "Tyre replacement",
      "Tyre balancing",
      "Wheel alignment",
      "Tyre puncture repair",
      "Wheel refurbishment",
    ],
  },
  {
    slug: "performance-upgrades",
    title: "Performance & Upgrades",
    icon: Rocket,
    summary: "ECU tuning, turbo and suspension upgrades for serious performance.",
    items: [
      "ECU coding & programming",
      "ECU tuning",
      "Performance exhaust installation",
      "Suspension upgrades",
      "Brake upgrades",
      "Turbo upgrades",
      "Intake system upgrades",
    ],
  },
  {
    slug: "body-cosmetic",
    title: "Body & Cosmetic",
    icon: Paintbrush,
    summary: "Accident repair, paintwork and detailing to restore showroom looks.",
    items: [
      "Accident repairs",
      "Dent removal",
      "Paintwork",
      "Headlight restoration",
      "Paint protection",
      "Ceramic coating",
      "Detailing",
    ],
  },
  {
    slug: "recovery-convenience",
    title: "Recovery & Convenience",
    icon: Truck,
    summary: "Breakdown recovery, inspections and mobile mechanic support.",
    items: [
      "Vehicle recovery",
      "Breakdown assistance",
      "Pre-purchase inspections",
      "Vehicle health checks",
      "Fleet maintenance",
      "Mobile mechanic services",
      "Pick-up & delivery service",
    ],
  },
  {
    slug: "additional-services",
    title: "Additional Services",
    icon: ClipboardList,
    summary: "Pre-registration checks, insurance work and warranty servicing.",
    items: [
      "Car inspection before registration and purchasing",
      "Insurance repair work",
      "Warranty servicing",
      "Used car inspections",
      "Road trip safety inspections",
    ],
  },
  {
    slug: "advanced-computer-diagnostics",
    title: "Advanced Computer Diagnostics",
    icon: Cpu,
    summary: "Dealership-level diagnostics powered by the Autel MaxiSYS Ultra S2.",
    note: "Using the Autel MaxiSYS Ultra S2, we provide dealership-level diagnostics for most vehicle makes and models.",
    items: [
      "Full vehicle health check",
      "Engine fault diagnosis",
      "Transmission diagnostics",
      "ABS & brake system diagnostics",
      "Airbag (SRS) diagnostics",
      "Steering & suspension system diagnostics",
      "Climate control (AC) diagnostics",
      "Battery & charging system testing",
      "TPMS (Tyre Pressure Monitoring System) diagnosis",
      "Electronic parking brake service",
      "Service light reset",
      "Oil service reset",
      "DPF regeneration & diagnostics (diesel vehicles)",
      "Injector coding",
      "Battery registration",
      "ECU coding & programming (supported vehicles)",
      "Live data analysis",
      "Component activation & system testing",
      "Pre-purchase diagnostic inspections",
      "Check engine light diagnosis",
    ],
  },
];
